/**
 * Central collection-name registry. Import names from here —
 * never hardcode collection strings in repositories.
 */
export const COLLECTIONS = {
  users: 'users',
  profiles: 'profiles',
  sessions: 'sessions',
  password_resets: 'password_resets',
  user_settings: 'user_settings',
  ai_quotas: 'ai_quotas',
  rush_solves: 'rush_solves',
  lesson_progress: 'lesson_progress',
  games: 'games',
  game_moves: 'game_moves',
  game_events: 'game_events',
  ratings: 'ratings',
  rating_history: 'rating_history',
  replays: 'replays',
  game_analysis: 'game_analysis',
  bot_profiles: 'bot_profiles',
  tournaments: 'tournaments',
  tournament_players: 'tournament_players',
  tournament_rounds: 'tournament_rounds',
  clubs: 'clubs',
  club_members: 'club_members',
  friends: 'friends',
  friend_requests: 'friend_requests',
  blocks: 'blocks',
  notifications: 'notifications',
  chat_channels: 'chat_channels',
  chat_messages: 'chat_messages',
  reports: 'reports',
  moderation_cases: 'moderation_cases',
  bans: 'bans',
  subscriptions: 'subscriptions',
  subscription_events: 'subscription_events',
  entitlements: 'entitlements',
  payments: 'payments',
  cosmetics: 'cosmetics',
  inventories: 'inventories',
  achievements: 'achievements',
  user_achievements: 'user_achievements',
  seasons: 'seasons',
  season_progress: 'season_progress',
  puzzles: 'puzzles',
  puzzle_attempts: 'puzzle_attempts',
  ai_sessions: 'ai_sessions',
  ai_usage: 'ai_usage',
  ai_jobs: 'ai_jobs',
  admin_users: 'admin_users',
  admin_audit_logs: 'admin_audit_logs',
  feature_flags: 'feature_flags',
  announcements: 'announcements',
  system_settings: 'system_settings',
  analytics_events: 'analytics_events',
} as const;

export type CollectionName = (typeof COLLECTIONS)[keyof typeof COLLECTIONS];
