/**
 * Public API of @nexus/engine. Import from here, not from internals.
 */
export {
  estimateMultiWinShare,
  winChanceCurve,
  winChanceFor,
  type MultiWinShare,
} from './eval/winChance.js';
export {
  BOARD_PRESETS,
  RULES_VERSION,
  type Action,
  type ApplyResult,
  type GameConfig,
  type GameEvent,
  type GameState,
  type Orientation,
  type PlayerIndex,
  type Pos,
  type RejectReason,
  type ValidationResult,
  type Wall,
} from './core/types.js';
export {
  canPlaceWallGeometry,
  getNeighbors,
  goalRowFor,
  isBlockedBetween,
  isInBoundsCell,
  isInBoundsWall,
  startPosFor,
  wallsEqual,
} from './core/board.js';
export {
  findShortestPath,
  getPathMetrics,
  hasPathToGoal,
  type PathMetrics,
  type ShortestPath,
} from './pathfinding/bfs.js';
export { getLegalMoves as getLegalPawnMoves } from './rules/moves.js';
export { getLegalWalls, validateWall } from './rules/walls.js';
export {
  applyMove,
  createGame,
  deserializeState,
  getLegalMoves,
  hashState,
  isGameOver,
  replayGame,
  serializeState,
  validateMove,
} from './rules/game.js';
export {
  buildReplay,
  REPLAY_VERSION,
  verifyReplay,
  type Replay,
  type ReplayVerification,
} from './replay/replay.js';
export {
  BALANCED_WEIGHTS,
  adaptiveBudgetMs,
  botAction,
  botActionShallow,
  BOTS,
  chooseBotAction,
  chooseDeepAction,
  evaluateFor,
  getBot,
  mulberry32,
  quip,
  topCandidates,
  type BanterTrigger,
  type BotDef,
  type CandidateAction,
  type DeepResult,
  type DeepSearchOptions,
  type EvalWeights,
  type ScoredAction,
  type SearchOptions,
} from './bots/index.js';
export {
  describeAction,
  mobilityOf,
  parseBestAction,
  reviewGame,
  REVIEW_THRESHOLDS,
  type GameReview,
  type MoveClass,
  type ReviewedMove,
  type ReviewLabel,
  type ReviewOptions,
} from './review/index.js';
export {
  dailyPuzzle,
  gradeAttempt,
  seededPuzzle,
  todayKey,
  type AttemptVerdict,
  type DailyPuzzle,
} from './puzzles/index.js';
export { QUICK_CHAT, isQuickChat, type QuickChatMessage } from './chat/index.js';
export {
  CHAOS_ROTATION_PLIES,
  SIEGE_WALL_BONUS,
  applyMultiMove,
  chooseMultiBotAction,
  createMultiGame,
  defaultSides,
  fogMap,
  getMultiLegalMoves,
  getMultiLegalWalls,
  gradeMultiAttempt,
  hashMultiState,
  hiddenWallCount,
  isGoal,
  isMultiGameOver,
  MULTI_BOT_DEFAULT,
  MULTI_PRESETS,
  MULTI_PUZZLE_NEED_GAIN,
  MULTI_RULES_VERSION,
  multiPuzzleDaily,
  pawnsAdjacent,
  presetForPlayers,
  replayMultiGame,
  seatTeams,
  seededMultiPuzzle,
  serializeMultiState,
  shortestToSide,
  startFor,
  teamMates,
  validateMultiMove,
  validateMultiWall,
  visibleWalls,
  type MultiAction,
  type MultiApplyResult,
  type MultiAttemptVerdict,
  type MultiBotOpts,
  type MultiConfig,
  type MultiOrientation,
  type MultiPos,
  type MultiPuzzle,
  type MultiRejectReason,
  type MultiState,
  type MultiValidation,
  type MultiWall,
  type SeatSide,
  type SidePath,
} from './multi/index.js';
