/** Mined lesson positions — generated by engine benchmark build-lessons. Verified legal by construction. */
export const LESSON_POSITIONS = {
 "opening_4ply": {
  "size": 9,
  "turn": 0,
  "pawns": [
   {
    "r": 2,
    "c": 4
   },
   {
    "r": 6,
    "c": 4
   }
  ],
  "walls": [],
  "wallsRemaining": [
   10,
   10
  ]
 },
 "opening_6ply": {
  "size": 9,
  "turn": 0,
  "pawns": [
   {
    "r": 3,
    "c": 4
   },
   {
    "r": 5,
    "c": 4
   }
  ],
  "walls": [],
  "wallsRemaining": [
   10,
   10
  ]
 },
 "opening_8ply": {
  "size": 9,
  "turn": 0,
  "pawns": [
   {
    "r": 4,
    "c": 4
   },
   {
    "r": 3,
    "c": 4
   }
  ],
  "walls": [],
  "wallsRemaining": [
   10,
   10
  ]
 },
 "choke_a": {
  "size": 9,
  "turn": 1,
  "pawns": [
   {
    "r": 2,
    "c": 4
   },
   {
    "r": 7,
    "c": 4
   }
  ],
  "walls": [
   {
    "r": 7,
    "c": 4,
    "orientation": "h"
   },
   {
    "r": 2,
    "c": 2,
    "orientation": "h"
   },
   {
    "r": 3,
    "c": 4,
    "orientation": "h"
   },
   {
    "r": 3,
    "c": 6,
    "orientation": "h"
   }
  ],
  "wallsRemaining": [
   8,
   8
  ],
  "solution": {
   "r": 2,
   "c": 3,
   "orientation": "v"
  },
  "needGain": 3,
  "solutionGain": 3
 },
 "choke_b": {
  "size": 9,
  "turn": 0,
  "pawns": [
   {
    "r": 3,
    "c": 5
   },
   {
    "r": 5,
    "c": 3
   }
  ],
  "walls": [
   {
    "r": 0,
    "c": 4,
    "orientation": "h"
   },
   {
    "r": 4,
    "c": 2,
    "orientation": "h"
   },
   {
    "r": 4,
    "c": 4,
    "orientation": "h"
   },
   {
    "r": 4,
    "c": 6,
    "orientation": "h"
   }
  ],
  "wallsRemaining": [
   8,
   8
  ],
  "solution": {
   "r": 4,
   "c": 0,
   "orientation": "h"
  },
  "needGain": 3,
  "solutionGain": 3
 },
 "choke_trap": {
  "size": 9,
  "turn": 0,
  "pawns": [
   {
    "r": 0,
    "c": 1
   },
   {
    "r": 7,
    "c": 4
   }
  ],
  "walls": [
   {
    "r": 0,
    "c": 3,
    "orientation": "h"
   },
   {
    "r": 1,
    "c": 3,
    "orientation": "h"
   },
   {
    "r": 0,
    "c": 4,
    "orientation": "h"
   },
   {
    "r": 1,
    "c": 4,
    "orientation": "h"
   },
   {
    "r": 1,
    "c": 5,
    "orientation": "v"
   },
   {
    "r": 1,
    "c": 1,
    "orientation": "h"
   },
   {
    "r": 1,
    "c": 6,
    "orientation": "h"
   },
   {
    "r": 0,
    "c": 0,
    "orientation": "v"
   },
   {
    "r": 6,
    "c": 7,
    "orientation": "h"
   },
   {
    "r": 0,
    "c": 2,
    "orientation": "h"
   },
   {
    "r": 6,
    "c": 5,
    "orientation": "h"
   },
   {
    "r": 6,
    "c": 3,
    "orientation": "h"
   }
  ],
  "wallsRemaining": [
   7,
   1
  ],
  "solution": {
   "r": 1,
   "c": 0,
   "orientation": "h"
  },
  "needGain": 3,
  "solutionGain": 4
 },
 "endgame_mate1": {
  "size": 9,
  "turn": 0,
  "pawns": [
   {
    "r": 7,
    "c": 4
   },
   {
    "r": 2,
    "c": 2
   }
  ],
  "walls": [],
  "wallsRemaining": [
   10,
   10
  ]
 },
 "midgame_maze": {
  "size": 9,
  "turn": 0,
  "pawns": [
   {
    "r": 5,
    "c": 4
   },
   {
    "r": 2,
    "c": 5
   }
  ],
  "walls": [
   {
    "r": 0,
    "c": 4,
    "orientation": "h"
   },
   {
    "r": 0,
    "c": 3,
    "orientation": "h"
   },
   {
    "r": 1,
    "c": 2,
    "orientation": "v"
   },
   {
    "r": 1,
    "c": 4,
    "orientation": "v"
   },
   {
    "r": 0,
    "c": 6,
    "orientation": "h"
   }
  ],
  "wallsRemaining": [
   5,
   10
  ]
 }
} as const;
